name: pipelinetest
on: push

env:
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  USERNAME: ${{ github.actor }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: user-step
        run: echo "${{ github.actor }}"
  deploy:
    runs-on: ubuntu-latest
    if: ! contains($COMMIT_MESSAGE , 'skip-deploy')
    needs:
      - test
    steps:
      - name: Schedule deployment
        run: echo "Runing deployment"
