name: pipelinetest
on: push

env:
  USERNAME: ${{ github.event.schedule.user.login }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: user-step
        run: echo "${{ github.event.schedule.user.login }}"
