name: pipelinetest
on: push

env:
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  USERNAME: ${{ github.actor }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: user-step
        run: echo "${{ github.actor }}"
