name: pipelinetest
on: push

env:
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  USERNAME: ${{ github.actor }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: user-step
        run: echo "${{ github.actor }}"
  deploy:
    if: contains(${{env.COMMIT_MESSAGE}}, 'skip-deploy') != true
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Schedule deployment
        run: echo "Runing deployment"
