name: pipelinetest
on: push

env:
  USERNAME: ${{ github.actor }}
  BRANCH_NAME: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: user-step
        run: echo "${{ github.actor }}"
      - name: branch-step
        run: echo "${{ github.ref }}"
  deploy:
    if: contains(github.event.head_commit.message, 'skip-deploy') != true
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Schedule deployment
        run: echo "Runing deployment"
